name: 'KiCad Gerber'
author: 'Emily McLean'
description: 'Generates gerber & drill files for a specified KiCad PCB and places them in a specified directory'
inputs:
  input-file:
    description: 'The PCB file to process'
    required: true
  output-directory:
    description: 'The directory in which to place the output'
    required: false
    default: "gerber"
  position-format:
    description: 'The position format to use. Options are gerber, csv, ascii, and none'
    required: false
    default: "none"
runs:
  using: 'docker'
  image: 'docker://ghcr.io/benmmclean/kicad-gerber:2.0.3'
  args:
    - ${{ inputs.input-file }}
    - ${{ inputs.output-directory }}
    - ${{ inputs.position-format }}
branding:
  icon: 'cpu'
  color: 'green'